[mgr]
ratio = [2, 4, 2]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true
linemode = "file_info"
show_hidden = true
show_symlink = true
scrolloff = 5
